kind: pipeline
name: default

steps:
- name: build
  image: rustlang/rust:nightly
  commands:
    - cargo build
- name: tests
  image: rustlang/rust:nightly
  commands:
    - cargo test --verbose --all
