known_pubkeys = ['LQaHiMmaBwE76yVoLubxtl5RKgG2blBrQkREWmtmgT8']
known_privkeys = ['AWxDWGKXZZOndWlvY5gvsbLzeRJEFpueNUoR/VCDKXMtBoeIyZoHATvrJWgu5vG2XlEqAbZuUGtCRERaa2aBPw==']
deny_pubkeys = []
deny_privkeys = []
